// Auto-generated by Tegaki. Do not edit manually.
import fontUrl from "./quicksand.ttf" with { type: "url" };
import glyphData from "./glyphData.json" with { type: "json" };
import glyphDataById from "./glyphDataById.json" with { type: "json" };

const bundle = {
  version: 0,
  family: "Quicksand",
  lineCap: "round",
  fontUrl,
  fontFaceCSS: `@font-face { font-family: 'Quicksand'; src: url(${fontUrl}); }`,
  unitsPerEm: 1000,
  ascender: 1160,
  descender: -288,
  glyphData,
  glyphDataById,
  features: ["ccmp", "liga", "locl", "vert", "vrt2"],
} as const;

export default bundle;
